In [1]:
%matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")

In [3]:
data_small=pd.read_csv("I:/Masters/SPRING 18/SPATIAL AND TEMPORAL/spatial/project/final/data2011on.csv")

In [4]:
data_small.head(5)

   Unnamed: 0        ID Case Number                    Date                   Block  IUCR   Primary Type              Description Location Description  Arrest  Domestic  Beat  District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year              Updated On   Latitude  Longitude                       Location
0           0  10000092    HY189866  03/18/2015 07:44:00 PM         047XX W OHIO ST  041A        BATTERY      AGGRAVATED: HANDGUN               STREET   False     False  1111      11.0  28.0            25.0      04B     1144606.0     1903566.0  2015  02/10/2018 03:50:01 PM  41.891399 -87.744385  (41.891398861, -87.744384567)
1           1  10000094    HY190059  03/18/2015 11:00:00 PM  066XX S MARSHFIELD AVE  4625  OTHER OFFENSE         PAROLE VIOLATION               STREET    True     False   725       7.0  15.0            67.0       26     1166468.0     1860715.0  2015  02/10/2018 03:50:01 PM  41.773372 -87.665319  (41.773371528, -87.665319468)
2           2  10000095    HY190052  03/18/2015 10:45:00 PM   044XX S LAKE PARK AVE  0486        BATTERY  DOMESTIC BATTERY SIMPLE            APARTMENT   False      True   222       2.0   4.0            39.0      08B     1185075.0     1875622.0  2015  02/10/2018 03:50:01 PM  41.813861 -87.596643   (41.81386068, -87.596642837)
3           3  10000096    HY190054  03/18/2015 10:30:00 PM    051XX S MICHIGAN AVE  0460        BATTERY                   SIMPLE            APARTMENT   False     False   225       2.0   3.0            40.0      08B     1178033.0     1870804.0  2015  02/10/2018 03:50:01 PM  41.800802 -87.622619  (41.800802415, -87.622619343)
4           4  10000097    HY189976  03/18/2015 09:00:00 PM        047XX W ADAMS ST  031A        ROBBERY           ARMED: HANDGUN             SIDEWALK   False     False  1113      11.0  28.0            25.0       03     1144920.0     1898709.0  2015  02/10/2018 03:50:01 PM  41.878065 -87.743354  (41.878064761, -87.743354013)

In [5]:
data_small=data_small.drop(["Case Number", "Domestic", "Beat", "Updated On", "Arrest"], 1)

In [7]:

datagb_crime=data_small.groupby("Primary Type")["Primary Type"].count()
datagb_crime.sort_values(ascending=False, inplace=True)
datagb_crime.head(50)

Primary Type
THEFT                                466759
BATTERY                              371439
CRIMINAL DAMAGE                      220552
NARCOTICS                            185925
ASSAULT                              130234
OTHER OFFENSE                        124543
BURGLARY                             122374
DECEPTIVE PRACTICE                   107893
MOTOR VEHICLE THEFT                   91164
ROBBERY                               82563
CRIMINAL TRESPASS                     52069
WEAPONS VIOLATION                     25641
PUBLIC PEACE VIOLATION                17665
OFFENSE INVOLVING CHILDREN            16068
PROSTITUTION                          10762
CRIM SEXUAL ASSAULT                    9982
INTERFERENCE WITH PUBLIC OFFICER       8283
SEX OFFENSE                            7035
HOMICIDE                               3740
ARSON                                  3148
GAMBLING                               3139
LIQUOR LAW VIOLATION                   2764
KIDNAPPING                             1546
STALKING                               1192
INTIMIDATION                            985
OBSCENITY                               314
CONCEALED CARRY LICENSE VIOLATION       154
NON-CRIMINAL                            128
PUBLIC INDECENCY                         84
OTHER NARCOTIC VIOLATION                 46
NON - CRIMINAL                           38
HUMAN TRAFFICKING                        36
NON-CRIMINAL (SUBJECT SPECIFIED)          6
Name: Primary Type, dtype: int64

In [8]:
crime_list=datagb_crime.index.values[0:25].tolist()
data_small=data_small[data_small["Primary Type"].isin(crime_list)]

In [9]:
data_small=data_small[data_small["Primary Type"]!="OTHER OFFENSE"]

In [10]:
severe_crime_list=["ARSON", "ASSAULT", "BATTERY", "CRIM SEXUAL ASSAULT", "CRIMINAL DAMAGE", "CRIMINAL TRESPASS", "HOMICIDE", "ROBBERY"]
data_small["severe"]=np.where(data_small['Primary Type'].isin(severe_crime_list), 1, 0)
data_small.head(5)

   Unnamed: 0        ID                    Date                  Block  IUCR Primary Type              Description Location Description  District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year   Latitude  Longitude                       Location  severe
0           0  10000092  03/18/2015 07:44:00 PM        047XX W OHIO ST  041A      BATTERY      AGGRAVATED: HANDGUN               STREET      11.0  28.0            25.0      04B     1144606.0     1903566.0  2015  41.891399 -87.744385  (41.891398861, -87.744384567)       1
2           2  10000095  03/18/2015 10:45:00 PM  044XX S LAKE PARK AVE  0486      BATTERY  DOMESTIC BATTERY SIMPLE            APARTMENT       2.0   4.0            39.0      08B     1185075.0     1875622.0  2015  41.813861 -87.596643   (41.81386068, -87.596642837)       1
3           3  10000096  03/18/2015 10:30:00 PM   051XX S MICHIGAN AVE  0460      BATTERY                   SIMPLE            APARTMENT       2.0   3.0            40.0      08B     1178033.0     1870804.0  2015  41.800802 -87.622619  (41.800802415, -87.622619343)       1
4           4  10000097  03/18/2015 09:00:00 PM       047XX W ADAMS ST  031A      ROBBERY           ARMED: HANDGUN             SIDEWALK      11.0  28.0            25.0       03     1144920.0     1898709.0  2015  41.878065 -87.743354  (41.878064761, -87.743354013)       1
5           5  10000098  03/18/2015 10:00:00 PM    049XX S DREXEL BLVD  0460      BATTERY                   SIMPLE            APARTMENT       2.0   4.0            39.0      08B     1183018.0     1872537.0  2015  41.805443 -87.604284  (41.805443345, -87.604283976)       1

In [11]:
print(len(data_small.groupby("Location Description")["Location Description"].count().index.values))

151

In [12]:
datagb_location=data_small.groupby("Location Description")["Location Description"].count()
datagb_location.sort_values(ascending=False, inplace=True)
datagb_location.head(50)

Location Description
STREET                               451843
RESIDENCE                            286001
APARTMENT                            239731
SIDEWALK                             217250
OTHER                                 70614
PARKING LOT/GARAGE(NON.RESID.)        59217
ALLEY                                 43470
RESIDENTIAL YARD (FRONT/BACK)         41943
SMALL RETAIL STORE                    39867
RESIDENCE-GARAGE                      36998
RESTAURANT                            36406
RESIDENCE PORCH/HALLWAY               35166
SCHOOL, PUBLIC, BUILDING              35102
VEHICLE NON-COMMERCIAL                33738
DEPARTMENT STORE                      29108
GROCERY FOOD STORE                    22594
GAS STATION                           21894
PARK PROPERTY                         16713
BAR OR TAVERN                         13729
CTA TRAIN                             10391
CTA PLATFORM                          10068
COMMERCIAL / BUSINESS OFFICE          10063
CONVENIENCE STORE                      9051
VACANT LOT/LAND                        9025
SCHOOL, PUBLIC, GROUNDS                8979
HOTEL/MOTEL                            8739
CTA BUS                                8330
DRUG STORE                             7601
BANK                                   7530
HOSPITAL BUILDING/GROUNDS              6556
POLICE FACILITY/VEH PARKING LOT        5659
CHA APARTMENT                          5604
CHA PARKING LOT/GROUNDS                5556
DRIVEWAY - RESIDENTIAL                 5148
ABANDONED BUILDING                     4930
CTA BUS STOP                           4769
CHURCH/SYNAGOGUE/PLACE OF WORSHIP      4413
CTA GARAGE / OTHER PROPERTY            4208
TAVERN/LIQUOR STORE                    4174
NURSING HOME/RETIREMENT HOME           4130
SCHOOL, PRIVATE, BUILDING              4059
GOVERNMENT BUILDING/PROPERTY           3921
ATM (AUTOMATIC TELLER MACHINE)         3823
ATHLETIC CLUB                          3729
CURRENCY EXCHANGE                      3163
TAXICAB                                2973
CTA STATION                            2850
CONSTRUCTION SITE                      2441
WAREHOUSE                              2191
SPORTS ARENA/STADIUM                   2070
Name: Location Description, dtype: int64

In [13]:
location_list=datagb_location.index.values[0:25].tolist()
data_small=data_small[data_small["Location Description"].isin(location_list)]
data_small.shape

(1788961, 19)

In [15]:
print(data_small.groupby("District")["District"].count())
print(data_small.groupby("Community Area")["Community Area"].count())

District
1.0      69807
2.0      74259
3.0      90968
4.0     105850
5.0      79288
6.0     108915
7.0     105555
8.0     120118
9.0      88210
10.0     82526
11.0    127580
12.0     84466
14.0     67356
15.0     81053
16.0     51870
17.0     52451
18.0     76999
19.0     80284
20.0     28585
22.0     57944
24.0     50808
25.0    104026
31.0        42
Name: District, dtype: int64
Community Area
0.0         12
1.0      25618
2.0      22355
3.0      24301
4.0      11936
5.0       9869
6.0      39066
7.0      27154
8.0      60152
9.0       1742
10.0      7461
11.0      7070
12.0      3151
13.0      5737
14.0     16401
15.0     22571
16.0     20953
17.0     10724
18.0      4054
19.0     32976
20.0     11164
21.0     16319
22.0     35834
23.0     59558
24.0     52650
25.0    119064
26.0     39423
27.0     35481
28.0     49909
29.0     56853
         ...
48.0      9865
49.0     48275
50.0      6598
51.0     12069
52.0      9279
53.0     29457
54.0      6251
55.0      3996
56.0     11982
57.0      6577
58.0     18097
59.0      7347
60.0     11217
61.0     35879
62.0      7059
63.0     17396
64.0      6528
65.0     13983
66.0     44448
67.0     52370
68.0     47061
69.0     45653
70.0     16157
71.0     52478
72.0      5947
73.0     21476
74.0      3681
75.0     14168
76.0      3286
77.0     16179
Name: Community Area, Length: 78, dtype: int64

In [16]:
datagb_destrict=data_small.groupby("District")["District"].count()
district_list=datagb_destrict.index.values[0:22].tolist()
data_small=data_small[data_small["District"].isin(district_list)]
data_small.shape

(1788918, 19)

In [17]:
data_small["District"]='D'+data_small['District'].astype(str)
data_small.head(2)

   Unnamed: 0        ID                    Date                  Block  IUCR Primary Type              Description Location Description District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year   Latitude  Longitude                       Location  severe
0           0  10000092  03/18/2015 07:44:00 PM        047XX W OHIO ST  041A      BATTERY      AGGRAVATED: HANDGUN               STREET    D11.0  28.0            25.0      04B     1144606.0     1903566.0  2015  41.891399 -87.744385  (41.891398861, -87.744384567)       1
2           2  10000095  03/18/2015 10:45:00 PM  044XX S LAKE PARK AVE  0486      BATTERY  DOMESTIC BATTERY SIMPLE            APARTMENT     D2.0   4.0            39.0      08B     1185075.0     1875622.0  2015  41.813861 -87.596643   (41.81386068, -87.596642837)       1

In [19]:
#make a dummy variable for district and primary type of crime
dummydf=pd.get_dummies(data_small,columns=["Primary Type","District"])
#we will just make a copy here in case we need to use it in the future
dummydf=dummydf.join(data_small[["District","Primary Type"]])
print(dummydf.shape)
dummydf.head(2)

(1788918, 65)

,Unnamed: 0,ID,Date,Block,IUCR,Description,Location Description,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_GAMBLING,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_KIDNAPPING,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1.0,District_D10.0,District_D11.0,District_D12.0,District_D14.0,District_D15.0,District_D16.0,District_D17.0,District_D18.0,District_D19.0,District_D2.0,District_D20.0,District_D22.0,District_D24.0,District_D25.0,District_D3.0,District_D4.0,District_D5.0,District_D6.0,District_D7.0,District_D8.0,District_D9.0,District,Primary Type
0,0,10000092,03/18/2015 07:44:00 PM,047XX W OHIO ST,041A,AGGRAVATED: HANDGUN,STREET,28.0,25.0,04B,1144606.0,1903566.0,2015,41.891399,-87.744385,"(41.891398861, -87.744384567)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,D11.0,BATTERY
2,2,10000095,03/18/2015 10:45:00 PM,044XX S LAKE PARK AVE,0486,DOMESTIC BATTERY SIMPLE,APARTMENT,4.0,39.0,08B,1185075.0,1875622.0,2015,41.813861,-87.596643,"(41.81386068, -87.596642837)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,D2.0,BATTERY

In [20]:
timedataf=dummydf.copy()
from datetime import datetime
format = '%m/%d/%Y %I:%M:%S %p'
dummydf["time_24hour"]=dummydf.Date.apply(lambda row: datetime.strptime(row, format).strftime("%H:%M"))
dummydf["Timeblock"]=dummydf.Date.apply(lambda row: str(3*int(int(datetime.strptime(row, format).strftime("%H"))/3)))
dummydf['Date_no_time']=dummydf.Date.apply(lambda row: datetime.strptime(row, format).strftime("%Y%m%d"))
dummydf["Weekday"]=dummydf.Date.apply(lambda row: datetime.strptime(row, format).strftime("%A"))
dummydf=pd.get_dummies(dummydf,columns=["Timeblock","Weekday"])
dummydf.shape

(1788918, 82)

In [22]:
dummydf.to_csv("I:/Masters/SPRING 18/SPATIAL AND TEMPORAL/spatial/project/final/datap1.csv")

Part 2

In [ ]:
chicago =pd.read_csv("I:/Masters/SPRING 18/SPATIAL AND TEMPORAL/spatial/project/final/datap1.csv")

In [23]:
chicago=dummydf

In [24]:
# drop all the NaNs in the dataframe
chicago = chicago.dropna()
chicago.shape

(1779710, 82)